buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // ✅ Required for com.android.library
        classpath "com.android.tools.build:gradle:7.2.2"
    }
}

plugins {
    id "maven-publish"
}

apply plugin: "com.android.library"

android {
    namespace "com.github.tranli.bmap_mobile_sdk"
    compileSdk 33

    defaultConfig {
        minSdk 21
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
    }
}

group = "com.github.tranli"
version = "5.2.0"

publishing {
    publications {
        release(MavenPublication) {
            artifactId = "bmap-mobile-sdk"

            // ✅ Publish prebuilt AAR
            artifact("$projectDir/libs/bmap-mobile-sdk-5.2.0.aar")
        }
    }
}
