plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace "com.github.tranli.bmap_mobile_sdk"
    compileSdk 33

    defaultConfig {
        minSdk 21
    }
}

group = "com.github.tranli"
version = "5.2.0"

publishing {
    publications {
        release(MavenPublication) {
            artifactId = "bmap-mobile-sdk"
            artifact("$projectDir/libs/bmap-mobile-sdk-5.2.0.aar")
        }
    }
}

